--- !ruby/object:Hosting
lists[:user]: []
lists[:admin]: []
title: Nikas
current_money_count: 50000
account_number: LT32154545787899
lists[:server]:
- !ruby/object:Server
  id: 1
  name: Small
  price: 10
- !ruby/object:Server
  id: 2
  name: Medium
  price: 30
- !ruby/object:Server
  id: 3
  name: Large
  price: 60
lists[:domain_end]: []
